image: "rust:latest"

stages:
    - lint
    - test
    - apply

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq postgresql-15 clang libpq-dev
        - rustup component add clippy
    script: cargo clippy -- --deny warnings

.test: &test
    stage: test
    before_script:
        - MODE=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - test "$MODE" == "release" && CARGO_FLAGS='--release' || CARGO_FLAGS=''
        - apt update -yqq
        - apt install -yqq sudo postgresql-15 locales clang libpq-dev
        - echo "en_US UTF-8" > /etc/locale.gen
        - locale-gen en_US.UTF-8
        - sudo -u postgres pg_ctlcluster 15 main start
        - sudo -u postgres psql --command "create role root WITH LOGIN ENCRYPTED PASSWORD '1234' SUPERUSER;";
        - sudo -u postgres psql --command "create database old with owner root;";
        - sudo -u postgres psql --command "create database new with owner root;";
        - export OLD_URL='postgres://root:1234@localhost/old'
        - export NEW_URL='postgres://root:1234@localhost/new'
    script:
        - cargo test $CARGO_FLAGS

test:debug:
    <<: *test

test:release:
    <<: *test

apply:release: &test
    stage: apply
    script:
        - sudo -u postgres pg_dump --schema-only new > new.dump
        - sudo -u postgres psql --file tests/diff.sql old
        - sudo -u postgres pg_dump --schema-only old > old.dump
        - diff -u old.dump new.dump

cache:
    paths:
        - $CARGO_HOME
        - target/
